"""Install Skill + .pipeline runtime into a target project."""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path
from typing import Optional


PACKAGE_ROOT = Path(__file__).resolve().parents[1]

# Docs that belong under .cursor/skills/ai-dev-pipeline/ (not runtime)
SKILL_DOC_FILES = ("SKILL.md", "reference.md", "README.md")
SKILL_DOC_DIRS = ("references",)


def copytree(src: Path, dst: Path, *, merge: bool = True) -> None:
    if not src.exists():
        raise FileNotFoundError(src)
    if dst.exists() and not merge:
        shutil.rmtree(dst)
    dst.mkdir(parents=True, exist_ok=True)
    for item in src.iterdir():
        target = dst / item.name
        if item.is_dir():
            copytree(item, target, merge=True)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(item, target)


def install_skill_docs(package_root: Path, skill_dst: Path) -> None:
    skill_dst.mkdir(parents=True, exist_ok=True)
    for name in SKILL_DOC_FILES:
        src = package_root / name
        if src.exists():
            shutil.copy2(src, skill_dst / name)
    for name in SKILL_DOC_DIRS:
        src = package_root / name
        if src.exists():
            copytree(src, skill_dst / name)


def install(target: Path, *, force_config: bool = False) -> None:
    target = target.resolve()
    target.mkdir(parents=True, exist_ok=True)

    skill_dst = target / ".cursor" / "skills" / "ai-dev-pipeline"
    if not (PACKAGE_ROOT / "SKILL.md").exists():
        raise FileNotFoundError(f"Missing SKILL.md in package root: {PACKAGE_ROOT}")
    install_skill_docs(PACKAGE_ROOT, skill_dst)

    pipeline = target / ".pipeline"
    (pipeline / "plans").mkdir(parents=True, exist_ok=True)
    (pipeline / "tasks" / "pending").mkdir(parents=True, exist_ok=True)
    (pipeline / "tasks" / "active").mkdir(parents=True, exist_ok=True)
    (pipeline / "tasks" / "done").mkdir(parents=True, exist_ok=True)
    (pipeline / "tasks" / "failed").mkdir(parents=True, exist_ok=True)
    (pipeline / "logs").mkdir(parents=True, exist_ok=True)
    (pipeline / "memory").mkdir(parents=True, exist_ok=True)
    (pipeline / "adaptations").mkdir(parents=True, exist_ok=True)

    prompts_src = PACKAGE_ROOT / "templates" / "prompts"
    copytree(prompts_src, pipeline / "prompts")

    scripts_src = PACKAGE_ROOT / "scripts"
    copytree(scripts_src, pipeline / "scripts")

    # Generic loop runner template
    run_loop_src = PACKAGE_ROOT / "templates" / "run_loop.py"
    if run_loop_src.exists():
        shutil.copy2(run_loop_src, pipeline / "run_loop.py")

    schema_src = PACKAGE_ROOT / "templates" / "task.schema.json"
    if schema_src.exists():
        shutil.copy2(schema_src, pipeline / "task.schema.json")

    examples_src = PACKAGE_ROOT / "examples"
    if examples_src.exists():
        copytree(examples_src, pipeline / "examples")

    config_dst = pipeline / "config.yaml"
    config_src = PACKAGE_ROOT / "templates" / "pipeline.config.yaml"
    if force_config or not config_dst.exists():
        shutil.copy2(config_src, config_dst)

    # Lightweight marker for skill discovery
    readme = pipeline / "README.md"
    if not readme.exists():
        readme.write_text(
            "# .pipeline\n\n"
            "Generated by `ai-dev-pipeline` install.\n\n"
            "```bash\n"
            "pip install -r <source>/requirements.txt  # PyYAML\n"
            "python .pipeline/scripts/run_pipeline.py --plan .pipeline/plans/your.md\n"
            "```\n",
            encoding="utf-8",
        )

    gitignore = pipeline / ".gitignore"
    gitignore.write_text(
        "logs/\ntasks/active/\nscripts/__pycache__/\n**/__pycache__/\n*.pyc\n",
        encoding="utf-8",
    )
    print(f"Installed skill -> {skill_dst}")
    print(f"Installed pipeline -> {pipeline}")
    print("Next:")
    print(f"  1. Put a plan in {pipeline / 'plans'}")
    print("  2. pip install PyYAML")
    print("  3. agent login   # or set CURSOR_API_KEY")
    print(f"  4. python {pipeline / 'scripts' / 'run_pipeline.py'} --plan .pipeline/plans/<file>")


def main(argv: Optional[list] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Install ai-dev-pipeline skill + .pipeline into a project"
    )
    parser.add_argument(
        "--target",
        default=".",
        help="Target project root (default: current directory)",
    )
    parser.add_argument(
        "--force-config",
        action="store_true",
        help="Overwrite existing .pipeline/config.yaml",
    )
    args = parser.parse_args(argv)
    try:
        install(Path(args.target), force_config=args.force_config)
    except Exception as exc:  # noqa: BLE001
        print(f"Install failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
